services:

  postgres:
    image: postgres:15
    container_name: postgres_container_locmns
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: locmns_db
      TZ: UTC
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - loc-net

  app:
    image: draifis/loc-mns-back:0.0.1-SNAPSHOT
    container_name: loc-back
    restart: always
    ports:
      - "8080:8080"
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: root
      DB_PASSWORD: root
      DB_NAME: locmns_db
      JWT_SECRET: azerty
      DDL_AUTO: update
      SQL_FILE: init
      SQL_INIT_MODE: never
    depends_on:
      - postgres
    networks:
      - loc-net

volumes:
  postgres_data:

networks:
  loc-net: